import { useMemo, useState } from 'react';
import { Download, FileSpreadsheet, FileText, CalendarRange, Megaphone, Users2 } from 'lucide-react';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { FilterDropdown } from '@/components/ui/FilterDropdown';
import { reports, getUserById } from '@/data';
import type { ReportType } from '@/types';
import { formatDate } from '@/utils/format';

const TYPE_OPTIONS = [
  { label: 'Weekly', value: 'weekly' },
  { label: 'Monthly', value: 'monthly' },
  { label: 'Campaign', value: 'campaign' },
  { label: 'Team', value: 'team' },
];

const TYPE_ICONS: Record<ReportType, typeof FileText> = {
  weekly: CalendarRange,
  monthly: CalendarRange,
  campaign: Megaphone,
  team: Users2,
};

export default function Reports() {
  const [type, setType] = useState('all');
  const [downloading, setDownloading] = useState<string | null>(null);

  const filtered = useMemo(() => reports.filter((r) => type === 'all' || r.type === type), [type]);

  const handleDownload = (id: string) => {
    setDownloading(id);
    setTimeout(() => setDownloading(null), 1200);
  };

  return (
    <div>
      <PageHeader
        title="Reports"
        description="Generate and export performance reports across your organization."
        action={<FilterDropdown label="Types" value={type} options={TYPE_OPTIONS} onChange={setType} />}
      />

      <div className="grid gap-4 lg:grid-cols-2">
        {filtered.map((report) => {
          const Icon = TYPE_ICONS[report.type];
          const generatedBy = getUserById(report.generatedBy);
          return (
            <Card key={report.id} className="p-5">
              <div className="flex items-start gap-3">
                <div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-brand-100 text-brand-600 dark:bg-brand-900/30 dark:text-brand-300">
                  <Icon className="size-5" />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="font-medium text-slate-800 dark:text-slate-100">{report.title}</p>
                  <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{report.description}</p>
                  <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-400">
                    <Badge className="capitalize">{report.type}</Badge>
                    <span>{report.period}</span>
                    <span>· {report.size}</span>
                  </div>
                  {generatedBy && (
                    <p className="mt-1 text-xs text-slate-400">
                      Generated by {generatedBy.name} on {formatDate(report.createdAt)}
                    </p>
                  )}
                </div>
              </div>

              <div className="mt-4 flex flex-wrap gap-2 border-t border-slate-100 pt-4 dark:border-slate-800">
                {report.formats.includes('pdf') && (
                  <Button
                    variant="outline"
                    size="sm"
                    isLoading={downloading === `${report.id}-pdf`}
                    onClick={() => handleDownload(`${report.id}-pdf`)}
                  >
                    <FileText className="size-4" /> Export PDF
                  </Button>
                )}
                {report.formats.includes('excel') && (
                  <Button
                    variant="outline"
                    size="sm"
                    isLoading={downloading === `${report.id}-excel`}
                    onClick={() => handleDownload(`${report.id}-excel`)}
                  >
                    <FileSpreadsheet className="size-4" /> Export Excel
                  </Button>
                )}
                <Button
                  size="sm"
                  isLoading={downloading === `${report.id}-download`}
                  onClick={() => handleDownload(`${report.id}-download`)}
                >
                  <Download className="size-4" /> Download
                </Button>
              </div>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
